// MERN/Week_2/Day_2/Practice/Luke APIwalker/Luke_APIwalker/src/components/Form.jsx
import React,{useState} from 'react'
import { useNavigate } from 'react-router-dom'

const Form = () => {
    const navigate = useNavigate();
    const [id, setId] = useState(0)
    const [cat, setCat] = useState("people")
    
    const search = (e) => {
        e.preventDefault()
        navigate(`/${cat}/${id}`)
        console.log('cat', cat)
    }
    return (
        <div className='row'>
            <form className='d-flex justify-content-center align-items-center gap-5' onSubmit={(e)=>search(e)}>
                <div className="d-flex justify-content-center align-items-center gap-3">
                    <label htmlFor="cat" className='h4'>Search for:</label>
                    <select className="form-select" onChange={(e)=>{setCat(e.target.value)}}>
                        <option value="people" >people</option>
                        <option value="planets">planets</option>
                    </select>
                </div>
                <div className="d-flex justify-content-center align-items-center gap-3">
                    <label htmlFor="id" className='h4'>ID:</label>
                    <input type="number" className='form-control' id='id' 
                    onChange={(e)=>{setId(e.target.value)}} value={id} />
                </div>
                <div className="d-flex justify-content-center align-items-center gap-3">
                    <button className='btn btn-primary btn-lg'>Search</button>
                </div>
            </form>
        </div>
    )
}


export default Form

// MERN/Week_4/Day_4/Luke-api/src/app/form/form.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';


@Component({
  selector: 'app-form',
  imports: [CommonModule, FormsModule],
  templateUrl: './form.component.html',
  styleUrl: './form.component.css'  
})
export class FormComponent {

  constructor(private router: Router){}

  onSubmit(data: any){
    this.router.navigate(['/display'], {state:{data: data}})
  }
}

<div class='row'>
    <form #data="ngForm" (ngSubmit)="onSubmit(data.value)" class='d-flex flex-column justify-content-center align-items-center gap-5 mt-5'>
        <div class="d-flex justify-content-center align-items-center gap-3">
            <label htmlFor="cat" class='h4'>Category:</label>
            <select  name="cat" class="form-select" ngModel>
                <option value="people" >people</option>
                <option value="planets">planets</option>
            </select>
        </div>
        <div class="d-flex justify-content-center align-items-center gap-3">
            <label htmlFor="id" class='h4'>ID:</label>
            <input name="id" type="number" class='form-control' ngModel/>
        </div>
        <div class="d-flex justify-content-center align-items-center gap-3">
            <button class='btn btn-primary btn-lg'>Search</button>
        </div>
    </form>
</div>
