// MERN/Week_2/Day_2/Practice/Luke APIwalker/Luke_APIwalker/src/components/Display.jsx
import React, { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import axios from 'axios';

const Display = () => {
    const { cat , id } = useParams();
    const [selected, setSelected] = useState(null)
    const navigate = useNavigate()

    useEffect(() => {
        axios.get(`https://swapi.dev/api/${cat}/${id}/`)
            .then(response => {
                console.log(response.data)
                setSelected(response.data)
            })
            .catch(error => {
                navigate('/error')
            });
        }, [cat,id]);

    return (
    <div>

        {(selected)&& <div>
        <h1>{selected.name}</h1>
        {(cat==="people")&&<div><h5>Height : {selected.height}</h5><h5>Mass : {selected.mass}</h5><h5>Eyes Color : {selected.eye_color}</h5><h5>Hair Color : {selected.hair_color}</h5></div>}
        {(cat==="planets")&&<div><h5>Climate : {selected.climate}</h5><h5>Terrain : {selected.terrain}</h5><h5>Surface Water : {selected.surface_water}</h5><h5>Population : {selected.population}</h5></div>} </div>}

    </div>
    )
}

export default Display

// MERN/Week_4/Day_4/Luke-api/src/app/display/display.component.ts
import { Component } from '@angular/core';
import { ApiService } from '../api.service';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';

@Component({
  selector: 'app-display',
  imports: [CommonModule],
  templateUrl: './display.component.html',
  styleUrl: './display.component.css'
})
export class DisplayComponent {

  data:any
  item:any

  constructor(private router:Router ,private apiService:ApiService){
    const navigation=this.router.getCurrentNavigation()
    this.data=navigation?.extras?.state?.['data'] || {}
  }

  ngOnInit():void{
    this.apiService.getOne(this.data.id,this.data.cat).subscribe({
      next: (data)=>this.item=data,
      error:(err)=>console.error(err),
      complete:()=>console.info('complete')
    })
  }

}

<div *ngIf="data.cat == 'people' " class="container  mt-5" style="width: 700px;">
    <h2 class="text-center">Submitted Data</h2>
    <div class="mt-5 p-5 border rounded shadow bg-light">
        <h4 class="mb-3">{{item.name}}</h4>
        <ul class="d-flex flex-column gap-3">
        <li><b>Height:</b> {{item.height}}</li>
        <li><b>Hair color:</b> {{item.hair_color}}</li>
        <li><b>Eye Color:</b> {{item.eye_color}}</li>
        <li><b>Skin Color:</b> {{item.skin_color}}</li>
        </ul>
    </div>
</div>

<div *ngIf="data.cat == 'planets' " class="container  mt-5" style="width: 700px;">
    <h2 class="text-center">Submitted Data</h2>
    <div class="mt-5 p-5 border rounded shadow bg-light">
        <h4 class="mb-3">{{item.name}}</h4>
        <ul class="d-flex flex-column gap-3">
        <li><b>Climate:</b> {{item.climate}}</li>
        <li><b>Terrain:</b> {{item.terrain}}</li>
        <li><b>Surface Water:</b> {{item.surface_water}}</li>
        <li><b>Population:</b> {{item.population}}</li>
        </ul>
    </div>
</div>
